version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    command:
      - start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    depends_on:
      - postgres
  minio:
    image: quay.io/minio/minio:RELEASE.2022-09-25T15-44-53Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_IDENTITY_OPENID_CONFIG_URL: "http://host.docker.internal:8080/realms/unic/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio
      MINIO_SERVER_URL: http://localhost:9001
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: eN60ijdnw4wBGRTmOLZI1K74nKimj58w
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
volumes:
  data:
  postgres_data:
    driver: local