---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-user1
  labels:
    name: spark-user1
data:
  spark-user1.conf: |
    spark.kubernetes.namespace=user1
    spark.kubernetes.executor.secrets.minio-secret-user1=/root/.aws
    spark.kubernetes.executor.secrets.spark-secret-user1=/etc/secret
    spark.kubernetes.executor.annotation.vault.hashicorp.com/role=internal-app-ns-user1
