---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  labels:
    name: spark
data:
  spark-defaults.conf: |
    spark.master=k8s://https://kubernetes.default.svc.cluster.local
    spark.submit.deployMode =client
    spark.kubernetes.container.image=ferlabcrsj/spark:3.3.1
    spark.executor.instances=2
    spark.executor.memory=1g
    spark.executor.cores=1
    spark.driver.blockManager.port=7777
    spark.driver.port=2222
    spark.driver.host=jupyter.default.svc.cluster.local
    spark.driver.bindAddress=0.0.0.0
    spark.hadoop.fs.s3a.endpoint=minio.default.svc.cluster.local:9000
    spark.hadoop.fs.s3a.connection.ssl.enabled=false
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.profile.ProfileCredentialsProvider
    spark.hadoop.com.amazonaws.services.s3.enableV4=true
    spark.jars.packages=org.apache.hadoop:hadoop-aws:3.2.4
    spark.authenticate=true
    spark.network.crypto.enabled=true