apiVersion: v1
kind: Secret
metadata:
  name: spark-secret-user1
type: Opaque
data:
  spark-secret: c3BhcmsuYXV0aGVudGljYXRlLnNlY3JldD1ybUVYbWhLS25ERnZncGtQUjVBYgo=
---
apiVersion: v1
kind: Secret
metadata:
  name: spark-secret-user1
  namespace: user1
type: Opaque
data:
  spark-secret.conf: c3BhcmsuYXV0aGVudGljYXRlLnNlY3JldD1ybUVYbWhLS25ERnZncGtQUjVBYgo=