apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/jupyter
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: jupyter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter
  labels:
    app: jupyter
    role: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
      role: service
  serviceName: jupyter
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'notebook-user1'
        vault.hashicorp.com/agent-inject-secret-minio: 'notebook/user1/minio'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/secret-volume-path-minio: "/home/jovyan/.aws"
        vault.hashicorp.com/agent-inject-file-minio: "credentials"
        vault.hashicorp.com/agent-inject-template-minio: |
          {{- with secret "notebook/user1/minio" -}}
          [default]
          aws_access_key_id = {{ .Data.data.access_key_id }}
          aws_secret_access_key = {{ .Data.data.secret_key }}
          aws_session_token = {{ .Data.data.session_token }}
          expiration = {{ .Data.data.expiration }}
          {{- end -}}
      labels:
        app: jupyter
        role: service
    spec:
      serviceAccountName: user1
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:100 /home/jovyan"]
          volumeMounts:
            - name: jupyter
              mountPath: /home/jovyan
        - name: append-conf-default
          imagePullPolicy: Never
          image: ferlabcrsj/setup-spark-config
          volumeMounts:
            - name: conf-volume
              mountPath: /etc/output
            - name: spark-default
              mountPath: /etc/input
        - name: append-conf-spark-user
          imagePullPolicy: Never
          image: ferlabcrsj/setup-spark-config
          volumeMounts:
            - name: conf-volume
              mountPath: /etc/output
            - name: spark-user
              readOnly: true
              mountPath: /etc/input
        - name: append-conf-spark-secret
          imagePullPolicy: Never
          image: ferlabcrsj/setup-spark-config
          volumeMounts:
            - name: conf-volume
              mountPath: /etc/output
            - name: spark-secret
              readOnly: true
              mountPath: /etc/input

      containers:
        - name: jupyter
          image: jupyter/all-spark-notebook
          ports:
            - name: jupyter
              containerPort: 8888
          volumeMounts:
            - name: jupyter
              mountPath: /home/jovyan
            - name: spark-secret
              readOnly: true
              mountPath: "/etc/secret"
            - name: conf-volume
              readOnly: true
              mountPath: "/usr/local/spark-3.3.1-bin-hadoop3/conf"
      volumes:
        - name: spark-secret
          secret:
            secretName: spark-secret-user1
        - name: jupyter
          persistentVolumeClaim:
            claimName: jupyter
        - name: spark-default
          configMap:
            name: spark-defaults
        - name: spark-user
          configMap:
            name: spark-user1
        - name: conf-volume
          emptyDir:
            sizeLimit: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
    role: service
spec:
  selector:
    app: jupyter
    role: service
  type: NodePort
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: driver
      port: 2222
      protocol: TCP
    - name: blockmanager
      port: 7777
      protocol: TCP
